import { v4 as uuidv4 } from 'uuid';

export const projectQuery = [
  {
    project: 'chartske',
    data: {
      buildId: uuidv4(),
      isFallback: false,
      is_interactive: false,
      theme: 'custom',
      custom_theme: {
        background: {
          alpha: 1,
          _type: 'color',
          hex: '#C8D5D5',
          hsv: {
            a: 1,
            s: 0.018181818181818243,
            v: 0.43137254901960786,
            _type: 'hsvaColor',
            h: 210.00000000000023,
          },
          rgb: {
            g: 109,
            _type: 'rgbaColor',
            a: 1,
            b: 110,
            r: 108,
          },
          hsl: {
            a: 1,
            s: 0.009174311926605536,
            _type: 'hslaColor',
            h: 210.00000000000023,
            l: 0.4274509803921569,
          },
        },
        text: {
          rgb: {
            a: 1,
            b: 255,
            r: 255,
            g: 255,
            _type: 'rgbaColor',
          },
          hsl: {
            a: 1,
            s: 0,
            _type: 'hslaColor',
            h: 200,
            l: 1,
          },
          alpha: 1,
          _type: 'color',
          hex: '#000000',
          hsv: {
            a: 1,
            s: 0,
            v: 1,
            _type: 'hsvaColor',
            h: 200,
          },
        },
      },
      meta_description:
        'A project aimed at creating a ranking of music by Kenyan artists based on popularity by leveraging on data from streaming platforms.',
      meta_image: '/kecharts-hero.webp',
      name: 'Chartske',
      intro:
        'An effort to rank music in Kenya using data from streaming platforms like Spotify and YouTube. Inspired by sites like Billboard 100, it is tailored specifically to Kenyan music, filling a gap in the industry where no similar ranking platform currently exists.',
      meta_title: 'Chartske',
      tags: [
        { name: 'Design' },
        { name: 'UI' },
        { name: 'API' },
        { name: 'Next.js' },
        { name: 'MongoDB' },
      ],
      content: [
        {
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 150,
            aspectRatio: 1.3333333333333333,
            height: 150,
          },
          _type: 'project_image_text',
          copy_heading: 'Logo',
          link_internal: null,
          cta_text: null,
          image: '/chartske-logo.svg',
          include_cta: 'none',
          copy: "The logo features the 'Macondo Swash Caps' font paired with a dancing figure icon, creating the appearance of dancing letters. A 'KE' superscript, representing Kenya, is also included to complete the design.",
          link_external: null,
          link_internal_type: null,
          image_alt: 'chartske logo',
          caption_position: null,
          caption: null,
          image_is_decorative: true,
          include_caption: false,
          link_file: null,
          copy_position: 'left',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Landing Page',
          copy: 'The main page consists a brief description of the platform, followed by the main chart consisting of kenyan songs from different genres and right below it an explore charts with links to other charts based on genre.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/chartske-home-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/chartske-home-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/chartske-home-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Chartske main page.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: false,
          copy_position: 'above',
          copy_heading: 'Main charts',
          copy: null,
          _type: 'project_image',
          image_size: 'full',
          devices: {
            desktop: {
              image: '/chartske-main-2-desktop.webp',
              width: 1024,
              height: 968,
            },
            tablet: {
              image: '/chartske-main-2-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/chartske-main-2-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt:
            'Screenshot of Chartske landing page - main chart and explore charts sections',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Charts',
          copy: 'You can browse the different music rankings broken down by genre on a dedicated charts page.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/chartske-explore-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/chartske-explore-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/chartske-explore-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Charts page and Kenyan drill chart list.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Search',
          copy: "The platform also features a search function that integrates with Spotify and YouTube APIs, allowing users to search for music directly. The search results include details such as an artist's subscriber or follower count and the number of views or plays a song has received.",
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/chartske-search-yt-desktop.webp',
              width: 2722,
              height: 1634,
            },
            tablet: {
              image: '/chartske-search-yt-tab.webp',
              width: 1544,
              height: 1285,
            },
            mobile: {
              image: '/chartske-search-yt-mobile.webp',
              width: 1056,
              height: 958,
            },
            image: null,
          },
          image_alt: 'Screenshot of Chartske search interface',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: false,
          copy_position: 'above',
          copy_heading: 'Spotify',
          copy: null,
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/chartske-search-spoti-desktop.webp',
              width: 3106,
              height: 1354,
            },
            tablet: {
              image: '/chartske-search-spoti-tab.webp',
              width: 1637,
              height: 1173,
            },
            mobile: {
              image: '/chartske-search-spoti-mobile.webp',
              width: 1025,
              height: 952,
            },
            image: null,
          },
          image_alt: 'Screenshot of Chartske search interface',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        // {
        //   copy: 'Github',
        //   image_is_decorative: true,
        //   image_alt: null,
        //   link_external: 'https://github.com/kei-en/muimbaji',
        //   copy_position: 'below',
        //   _type: 'project_image',
        //   link_internal: null,
        //   link_internal_type: null,
        //   devices: {
        //     desktop: {
        //       image: null,
        //     },
        //     tablet: {
        //       image: null,
        //     },
        //     mobile: {
        //       image: null,
        //     },
        //     image: null,
        //   },
        //   copy_heading: 'View Project',
        //   include_cta: 'external',
        //   link_file: null,
        //   image_size: 'small',
        //   include_caption: false,
        //   include_copy: true,
        //   cta_text: 'production',
        //   caption: null,
        //   image_dimensions: {
        //     _type: 'sanity.imageDimensions',
        //     width: 2400,
        //     aspectRatio: 1.5,
        //     height: 1600,
        //   },
        // },
        {
          copy: 'Website',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://kecharts.vercel.app',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            desktop: {
              image: null,
            },
            tablet: {
              image: null,
            },
            mobile: {
              image: null,
            },
            image: null,
          },
          image: null,
          copy_heading: 'View Project',
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'website',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
      ],
    },
  },
  {
    project: 'muimbaji',
    data: {
      buildId: uuidv4(),
      isFallback: false,
      is_interactive: false,
      theme: 'custom',
      custom_theme: {
        background: {
          alpha: 1,
          _type: 'color',
          hex: '#3a3122',
          name: 'bg-red-500',
          hsv: {
            a: 1,
            s: 0.018181818181818243,
            v: 0.43137254901960786,
            _type: 'hsvaColor',
            h: 210.00000000000023,
          },
          rgb: {
            g: 109,
            _type: 'rgbaColor',
            a: 1,
            b: 110,
            r: 108,
          },
          hsl: {
            a: 1,
            s: 0.009174311926605536,
            _type: 'hslaColor',
            h: 210.00000000000023,
            l: 0.4274509803921569,
          },
        },
        text: {
          rgb: {
            a: 1,
            b: 255,
            r: 255,
            g: 255,
            _type: 'rgbaColor',
          },
          hsl: {
            a: 1,
            s: 0,
            _type: 'hslaColor',
            h: 200,
            l: 1,
          },
          alpha: 1,
          _type: 'color',
          hex: '#ffffff',
          hsv: {
            a: 1,
            s: 0,
            v: 1,
            _type: 'hsvaColor',
            h: 200,
          },
        },
      },
      meta_description:
        'A project aimed at making an artist showcase website, making it a onestop shop for anything related to the artist',
      meta_image: '/muimbaji-hero-image.webp',
      name: 'Muimbaji',
      intro:
        'The goal of this project was to create a comprehensive website for an artist showcase. The site serves as the primary resource for all information about the artist, featuring integrated audio and video players, as well as an online store where fans can purchase products. It centralizes all relevant information about the artist in one convenient location.',
      meta_title: 'Muimbaji',
      tags: [
        { name: 'Design' },
        { name: 'UI' },
        { name: 'UX' },
        { name: 'Next.js' },
      ],
      content: [
        {
          include_copy: false,
          copy_position: null,
          copy_heading: 'Logo',
          copy: null,
          _type: 'project_image',
          devices: {
            desktop: {
              image: null,
            },
            tablet: {
              image: null,
            },
            mobile: {
              image: null,
            },
            image: '/muimbaji-logo.png',
            width: 150,
            height: 150,
          },
          image_alt: null,
          include_caption: true,
          caption:
            'The logo. It comes from the working name "Fishbowl", before switching to muimbaji as it fit more with the final outcome.',
          image_is_decorative: true,
          image_size: 'small',
          include_cta: 'none',
          link_file: null,
          link_internal_type: null,
          cta_text: null,
          link_internal: null,
          link_external: null,
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Intro',
          copy: null,
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/homepage-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/homepage-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/homepage-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji intro page with the menu open.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Intro',
          copy: 'The introduction page is divided into four sections that introduce the artist and showcase their most recent music video, forthcoming events, and releases.',
          _type: 'project_image',
          image_size: 'full',
          devices: {
            desktop: {
              image: null,
            },
            tablet: {
              image: null,
            },
            mobile: {
              image: null,
            },
            image: '/hompage-desktop-2.webp',
            width: 2400,
            height: 1600,
          },
          image_alt:
            'Screenshot of Muimbaji intro page - about, upcoming events, and latest releases sections.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Music',
          copy: "The artist's discography is broken down into tracks and albums on the music page.",
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/musicpage-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/musicpage-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/musicpage-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji intro page with the menu open.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Music player',
          copy: 'The custom audio player located on the same page allows you to play the tracks on the music page.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/controlbar-desktop.webp',
              width: 1080,
              height: 200,
            },
            tablet: {
              image: '/controlbar-tab.webp',
              width: 810,
              height: 200,
            },
            mobile: {
              image: '/controlbar-mobile.webp',
              width: 375,
              height: 150,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji audio player interface.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'full',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Media',
          copy: 'The media page is separated into videos and images sections featuring music videos and photos of the artist.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/videopage-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/videopage-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/videopage-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji media page, videos section.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: false,
          copy_position: 'none',
          copy_heading: 'Media',
          copy: 'The media page is separated into videos and images sections featuring music videos by the artist and photos of them.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/imagepage-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/imagepage-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/imagepage-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji media page, images section.',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Shop',
          copy: "The shop page directs visitors to an ecommerce site where the artist's products can be purchased.",
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/shoppage-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/shoppage-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/shoppage-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji shop page',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          include_copy: true,
          copy_position: 'above',
          copy_heading: 'Payment processing',
          copy: 'Stripe serves as the payment processing gateway. The shop itself is created with Next.js and Strapi, and is linked to PostgreSQL for data storage and Auth0 for user authentication and management.',
          _type: 'project_image',
          devices: {
            desktop: {
              image: '/payment-desktop.webp',
              width: 1024,
              height: 568,
            },
            tablet: {
              image: '/payment-tab.webp',
              width: 810,
              height: 980,
            },
            mobile: {
              image: '/payment-mobile.webp',
              width: 375,
              height: 612,
            },
            image: null,
          },
          image_alt: 'Screenshot of Muimbaji shop page',
          include_caption: false,
          caption: null,
          image_is_decorative: false,
          image_size: 'large',
          link_file: null,
          link_internal: null,
          cta_text: null,
          link_internal_type: null,
          link_external: null,
          include_cta: 'none',
        },
        {
          copy: 'Github',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://github.com/kei-en/muimbaji',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            desktop: {
              image: null,
            },
            tablet: {
              image: null,
            },
            mobile: {
              image: null,
            },
            image: null,
          },
          copy_heading: 'View Project',
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
        {
          copy: 'Website',
          image_is_decorative: true,
          image_alt: null,
          link_external: 'https://muimbaji.vercel.app',
          copy_position: 'below',
          _type: 'project_image',
          link_internal: null,
          link_internal_type: null,
          devices: {
            desktop: {
              image: null,
            },
            tablet: {
              image: null,
            },
            mobile: {
              image: null,
            },
            image: null,
          },
          image: null,
          copy_heading: null,
          include_cta: 'external',
          link_file: null,
          image_size: 'small',
          include_caption: false,
          include_copy: true,
          cta_text: 'production',
          caption: null,
          image_dimensions: {
            _type: 'sanity.imageDimensions',
            width: 2400,
            aspectRatio: 1.5,
            height: 1600,
          },
        },
      ],
    },
  },
];
